server:
  port: 9200
spring:
  application:
    name: gondar-registry
eureka:
  instance:
    hostname: gondar-registry
  client:
    service-url:
      defaultZone: http://127.0.0.1:9200/eureka/
    register-with-eureka: false
    fetch-registry: false